version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "org.apache.kafka:*"
      - dependency-name: "com.solacesystems:*"
