version: 3

project:
  locator: SolaceProducts_pubsubplus-connector-kafka-source
  id: SolaceProducts_pubsubplus-connector-kafka-source
  name: pubsubplus-connector-kafka-source
  teams: []
  labels:
    - java

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
